/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uasisna;
import static uasisna.dbkoneksi.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author isnajaya
 * TGL 24 Mei 2025
 */
public class fpariwisata extends javax.swing.JFrame {
     DefaultTableModel dtm = new DefaultTableModel();
    /**
     * Creates new form fMahasiswa
     * @throws java.sql.SQLException
     */
    public fpariwisata() throws SQLException {
        initComponents();
        tmhs.setModel(dtm);
        dtm.addColumn("NAMA");
        dtm.addColumn("LOKASI");
        dtm.addColumn("DESKRIPSI");
        dtm.addColumn("KOMENTAR");
        
        lsDtMhs();
        fieldEnabled(false);
        tombol(false);
        cBARU.setEnabled(true);
        cTUTUP.setEnabled(true);
        
                
    }
    private void fieldEnabled(boolean opsi){
        TXNAMA.setEditable(opsi);
        TXLOKASI.setEditable(opsi);
        TXDESKRIPSI.setEditable(opsi);
        TXKOMENTAR.setEditable(opsi);
    }
    private void tombol(boolean opsi){
        cBARU.setEnabled(opsi);
        cUBAH.setEnabled(opsi);
        cHAPUS.setEnabled(opsi);
        cTUTUP.setEnabled(opsi);
    }
    private void clearfrom(){
        TXNAMA.setText("");
        TXLOKASI.setText("");
        TXKOMENTAR.setText("");
        TXDESKRIPSI.setText("");
    }
        
        
    
    private void lsDtMhs() throws SQLException {
    Connection cnn = koneksi();
    dtm.getDataVector().removeAllElements();
    dtm.fireTableDataChanged();

    if (!cnn.isClosed()) {
        PreparedStatement ps = cnn.prepareStatement("SELECT * FROM wisata;");
        ResultSet rs = ps.executeQuery();
        while (rs.next()) {
            Object[] dta = new Object[4];
            dta[0] = rs.getString("NAMA");
            dta[1] = rs.getString("LOKASI");
            dta[2] = rs.getString("DESKRIPSI");
            dta[3] = rs.getString("KOMENTAR");
            dtm.addRow(dta);
        }
        cnn.close();
    }
}

   private void storeData() throws SQLException {
    Connection cnn = koneksi();
    if (!cnn.isClosed()) {
        PreparedStatement ps = cnn.prepareStatement("INSERT INTO wisata(NAMA, LOKASI, DESKRIPSI, KOMENTAR) VALUES(?,?,?,?);");
        ps.setString(1, TXNAMA.getText());
        ps.setString(2, TXLOKASI.getText());
        ps.setString(3, TXDESKRIPSI.getText());
        ps.setString(4, TXKOMENTAR.getText());
        ps.executeUpdate();
        cnn.close();
    }
}
    
    private void updateData() throws SQLException {
    Connection cnn = koneksi();
    if (!cnn.isClosed()) {
        PreparedStatement ps = cnn.prepareStatement("UPDATE wisata SET LOKASI=?, DESKRIPSI=?, KOMENTAR=? WHERE NAMA=?");
        ps.setString(1, TXLOKASI.getText());
        ps.setString(2, TXDESKRIPSI.getText());
        ps.setString(3, TXKOMENTAR.getText());
        ps.setString(4, TXNAMA.getText());
        ps.executeUpdate();
        cnn.close();
    }
}

    private void destoryData() throws SQLException {
    Connection cnn = koneksi();
    if (!cnn.isClosed()) {
        PreparedStatement ps = cnn.prepareStatement("DELETE FROM wisata WHERE NAMA=?");
        ps.setString(1, TXNAMA.getText());
        ps.executeUpdate();
        cnn.close();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TXNAMA = new javax.swing.JTextField();
        TXLOKASI = new javax.swing.JTextField();
        TXDESKRIPSI = new javax.swing.JTextField();
        TXKOMENTAR = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tmhs = new javax.swing.JTable();
        cBARU = new javax.swing.JButton();
        cUBAH = new javax.swing.JButton();
        cHAPUS = new javax.swing.JButton();
        cTUTUP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Adobe Fan Heiti Std B", 0, 18)); // NOI18N
        setForeground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel1.setText("Daftar Tempat Wisata");

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel2.setText("NAMA");

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel3.setText("LOKASI");

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel4.setText("DESKRIPSI");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel5.setText("KOMENTAR");

        TXNAMA.setBackground(new java.awt.Color(204, 204, 255));
        TXNAMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXNAMAActionPerformed(evt);
            }
        });

        TXLOKASI.setBackground(new java.awt.Color(204, 204, 255));
        TXLOKASI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXLOKASIActionPerformed(evt);
            }
        });

        TXDESKRIPSI.setBackground(new java.awt.Color(204, 204, 255));
        TXDESKRIPSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXDESKRIPSIActionPerformed(evt);
            }
        });

        TXKOMENTAR.setBackground(new java.awt.Color(204, 204, 255));
        TXKOMENTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXKOMENTARActionPerformed(evt);
            }
        });

        tmhs.setBackground(new java.awt.Color(153, 153, 153));
        tmhs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tmhs.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                tmhsMouseDragged(evt);
            }
        });
        tmhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tmhsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tmhs);

        cBARU.setBackground(new java.awt.Color(204, 204, 204));
        cBARU.setText("Baru");
        cBARU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBARUActionPerformed(evt);
            }
        });

        cUBAH.setBackground(new java.awt.Color(204, 204, 204));
        cUBAH.setText("ubah");
        cUBAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cUBAHActionPerformed(evt);
            }
        });

        cHAPUS.setBackground(new java.awt.Color(204, 204, 204));
        cHAPUS.setText("Hapus");
        cHAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cHAPUSActionPerformed(evt);
            }
        });

        cTUTUP.setBackground(new java.awt.Color(204, 204, 204));
        cTUTUP.setText("Tutup");
        cTUTUP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cTUTUPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TXNAMA, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TXLOKASI, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(TXKOMENTAR, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TXDESKRIPSI, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(cBARU)
                                .addGap(18, 18, 18)
                                .addComponent(cUBAH)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cHAPUS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cTUTUP))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXNAMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(2, 2, 2)
                .addComponent(TXLOKASI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(23, 23, 23)
                .addComponent(TXDESKRIPSI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TXKOMENTAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBARU)
                    .addComponent(cUBAH)
                    .addComponent(cHAPUS)
                    .addComponent(cTUTUP))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXNAMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXNAMAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXNAMAActionPerformed

    private void TXLOKASIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXLOKASIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXLOKASIActionPerformed

    private void TXDESKRIPSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXDESKRIPSIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXDESKRIPSIActionPerformed

    private void TXKOMENTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXKOMENTARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXKOMENTARActionPerformed

    private void cBARUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBARUActionPerformed

    if (cBARU.getText().equals("Baru")) {
        cBARU.setText("Simpan");
        cTUTUP.setText("Batal");
        cUBAH.setEnabled(false);
        cHAPUS.setEnabled(false);
        clearfrom();
        fieldEnabled(true);
    } else {
        if (!TXNAMA.getText().equals("")) {
            try {
                // Simpan data ke database
                storeData();
                // Perbarui tabel setelah data disimpan
                lsDtMhs();
            } catch (SQLException ex) {
                Logger.getLogger(fpariwisata.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        cBARU.setText("Baru");
        cTUTUP.setText("Tutup");
        clearfrom();
        fieldEnabled(false);
    }


    }//GEN-LAST:event_cBARUActionPerformed

    private void cUBAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cUBAHActionPerformed

      
    if (cUBAH.getText().equals("Ubah")) {
        cUBAH.setText("Simpan");
        cTUTUP.setText("Batal");
        cBARU.setEnabled(false);
        cHAPUS.setEnabled(false);
        fieldEnabled(true);
        TXNAMA.setEditable(false);
    } else {
        try {
            // Update data setelah diubah
            updateData();
            // Refresh tabel
            lsDtMhs();
            clearfrom();
            fieldEnabled(false);
            cUBAH.setText("Ubah");
            cTUTUP.setText("Tutup");
            cBARU.setEnabled(true);
        } catch (SQLException ex) {
            Logger.getLogger(fpariwisata.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    }//GEN-LAST:event_cUBAHActionPerformed

    private void cHAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cHAPUSActionPerformed
      
       
    int jwb = JOptionPane.showOptionDialog(
            this,
            "Yakin akan menghapus data " + TXNAMA.getText() + "?",
            "Konfirmasi Hapus Data",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null, null, null);

    if (jwb == JOptionPane.YES_OPTION) {
        try {
            destoryData();
            lsDtMhs(); // refresh tabel setelah data dihapus
            clearfrom();
            cUBAH.setEnabled(false);
            cHAPUS.setEnabled(false);
        } catch (SQLException ex) {
            Logger.getLogger(fpariwisata.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    }//GEN-LAST:event_cHAPUSActionPerformed

    private void cTUTUPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTUTUPActionPerformed
    if(cTUTUP.getText().equals("TUTUP")){
        int opsi =JOptionPane.showOptionDialog(this,
             "yakin akn menutup form?",
             "konfirmasi tutup form?",
             JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,null,null);
     if (opsi == JOptionPane.YES_OPTION){
        System.exit(0);
    }//GEN-LAST:event_cTUTUPActionPerformed
   }else{
    cTUTUP.setText("Tutup");
    cBARU.setText("Baru");
    cUBAH.setText("Ubah");
    
    fieldEnabled(false);
    }
    
    }
    private void tmhsMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tmhsMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_tmhsMouseDragged

    private void tmhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tmhsMouseClicked

    TXNAMA.setText(tmhs.getValueAt(tmhs.getSelectedRow(), 0).toString());
    TXLOKASI.setText(tmhs.getValueAt(tmhs.getSelectedRow(), 1).toString());
    TXDESKRIPSI.setText(tmhs.getValueAt(tmhs.getSelectedRow(), 2).toString());
    TXKOMENTAR.setText(tmhs.getValueAt(tmhs.getSelectedRow(), 3).toString());
    cHAPUS.setEnabled(true);
    cUBAH.setEnabled(true);

    }//GEN-LAST:event_tmhsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fpariwisata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fpariwisata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fpariwisata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fpariwisata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new fpariwisata().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(fpariwisata.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TXDESKRIPSI;
    private javax.swing.JTextField TXKOMENTAR;
    private javax.swing.JTextField TXLOKASI;
    private javax.swing.JTextField TXNAMA;
    private javax.swing.JButton cBARU;
    private javax.swing.JButton cHAPUS;
    private javax.swing.JButton cTUTUP;
    private javax.swing.JButton cUBAH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tmhs;
    // End of variables declaration//GEN-END:variables

}